// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjEPHqJRugINfin7V7yn5GsZLzWxLx57o',
    appId: '1:338235999759:android:b7faba93cd0c5a9e05057a',
    messagingSenderId: '338235999759',
    projectId: 'nectar-40168',
    storageBucket: 'nectar-40168.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEayya649sHVg875YZf-wyciRiRte2T20',
    appId: '1:338235999759:ios:affbfaf22239b26305057a',
    messagingSenderId: '338235999759',
    projectId: 'nectar-40168',
    storageBucket: 'nectar-40168.appspot.com',
    androidClientId: '338235999759-7d8vjp8l9shn5pc87cep4uptg2urltku.apps.googleusercontent.com',
    iosClientId: '338235999759-ufrrddngh6vdenvbso2pg5b1sfq8quic.apps.googleusercontent.com',
    iosBundleId: 'com.example.nectarUi',
  );
}
